### ISSUE TITLE
python3.10不能安装上opencv_python==4.5.5.62

### ISSUE THREAD

**Issue by UQJRlex** [NaiboWang/Bilibili-XMLSubtitle-to-ASS#1]
python3.10不能安装opencv_python==4.5.5.62，安装过程中注意到python3.10不能安装需要的pyparsing、numpy低版本，除非再安装另一个低版本的python，要么需要依赖库能够更新。

**Comment by NaiboWang** [comment]
已删除opencv requirement，因为不需要了
