### ISSUE TITLE
希望改弹幕匹配视频规则为模糊匹配

### ISSUE THREAD

**Issue by FinnRaze** [NaiboWang/Bilibili-XMLSubtitle-to-ASS#2]
you-get下载的视频及弹幕不是完全同名的，这时xml弹幕会被跳过。
例如1.mp4 和 1.cmt.xml，工具会提示无需转换。只有改名才行，如果规则设为xml文件名包含视频文件名就好了。

**Comment by NaiboWang** [comment]
工具已失效，不再开发新功能。
