### ISSUE TITLE
请问为什么生成的ass文件里Events是空的

### ISSUE THREAD

**Issue by org-org-org** [NaiboWang/Bilibili-XMLSubtitle-to-ASS#4]
![image](https://github.com/NaiboWang/Bilibili-XMLSubtitle-to-ASS/assets/92204592/a3189752-123b-4ca2-8a51-a739c21e4e6f)
![image](https://github.com/NaiboWang/Bilibili-XMLSubtitle-to-ASS/assets/92204592/8eb0e0e1-a296-4a92-bdaa-bc97396c02b0)
![image](https://github.com/NaiboWang/Bilibili-XMLSubtitle-to-ASS/assets/92204592/3ab21a6a-b650-4889-9869-949feb072446)
![image](https://github.com/NaiboWang/Bilibili-XMLSubtitle-to-ASS/assets/92204592/adcc5d44-bea7-4e88-90ae-f9f17b72afa4)
![image](https://github.com/NaiboWang/Bilibili-XMLSubtitle-to-ASS/assets/92204592/a5310b30-76df-4c60-bf7f-43fd7ea10009)
是这个xml文件的格式有问题吗

**Comment by NaiboWang** [comment]
转换器只适用于用Windows应用商店的Bilibili应用下载的XML弹幕文件，请确认。
另外就是Windows应用商店的Bilibili应用已经停止维护了，因此这个工具已经差不多不太能使用了，现在还可以暂时用一下，等将来Windows应用商店的Bilibili应用彻底用不了之后这个也就用不了了。

**Comment by org-org-org** [comment]
好的，谢谢
